[package]

name = "openstack"
description = "OpenStack SDK for Rust"
version = "0.3.2"
authors = ["Dmitry Tantsur <divius.inside@gmail.com>"]
homepage = "https://dtantsur.github.io/rust-openstack/openstack/"
repository = "https://github.com/dtantsur/rust-openstack"
documentation = "https://dtantsur.github.io/rust-openstack/openstack/"
readme = "README.md"
license = "Apache-2.0"
keywords = ["api", "cloud", "openstack"]
categories = ["api-bindings"]
edition = "2018"

[features]

default = ["compute", "image", "network", "native-tls", "object-storage"]
compute = []
image = []
network = []
native-tls = ["reqwest/default-tls", "osauth/native-tls"]
object-storage = ["tokio", "tokio-util"]
rustls = ["reqwest/rustls-tls", "osauth/rustls"]

[dependencies]

async-trait = "^0.1"
chrono = { version = "^0.4", features = ["serde"] }
eui48 = { version = "^0.4.0", features = ["serde"] }
fallible-iterator = "^0.2.0"
futures = "^0.3"
ipnet = { version = "^2.0", features = ["serde"] }
log = "^0.4"
osauth = { git = "https://github.com/dtantsur/rust-osauth", branch = "async", default-features = false, features = ["stream"] }
osproto = "^0.2.0"
reqwest = { version = "^0.10", default-features = false, features = ["gzip", "json", "stream"] }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde_yaml = "^0.8"
tokio = { version = "^0.2", optional = true }
tokio-util = { version = "^0.2", features = ["codec"], optional = true }
waiter = "^0.1"

[dev-dependencies]
env_logger = "^0.7"

[lib]

name = "openstack"
path = "src/lib.rs"

[badges]
travis-ci = { repository = "dtantsur/rust-openstack" }
